import { Scale, ChevronLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
    return (
        <main className="py-16 lg:py-24 bg-background">
            <div className="wrapper max-w-3xl">
                {/* Updated Back Link */}
                <Link href="/" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-muted-foreground hover:text-primary mb-12 transition-all group">
                    <div className="p-1 rounded-md bg-secondary/50 group-hover:bg-primary/10 border border-foreground/5">
                        <ChevronLeft className="size-4" />
                    </div>
                    Back to Home
                </Link>

                <div className="space-y-12">
                    <div className="space-y-4 border-b-2 border-foreground/5 pb-8">
                        <div className="flex items-center gap-2 text-primary font-bold uppercase tracking-[0.2em] text-[10px]">
                            <ShieldCheck className="size-4" /> {/* Swapped Scale for ShieldCheck for a "Security" vibe */}
                            Atlash Legal Framework
                        </div>
                        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Terms of Service</h1>
                        <p className="text-muted-foreground font-medium">Infrastructure Protocol Version: 1.0.4 — March 2026</p>
                    </div>

                    <div className="space-y-8 text-lg text-muted-foreground leading-relaxed font-medium">
                        <section className="space-y-4">
                            <h2 className="text-xl font-black text-foreground uppercase tracking-tight">1. Operational Protocol</h2>
                            <p>By accessing the Atlash Hub, you agree to maintain the integrity of the infrastructure network. Any attempt to provide fraudulent data, malicious scripts, or unauthorized system entries will result in immediate revocation of deployment access and a permanent ban from the System Directory.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-black text-foreground uppercase tracking-tight">2. Intellectual Property & Assets</h2>
                            <p>Lead Architects retain full intellectual property rights to the technical specifications and deployments submitted to Atlash. By listing an asset, you grant Atlash Hub a worldwide license to index and display your system node for the purpose of procurement discovery and reliability benchmarking.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-black text-foreground uppercase tracking-tight">3. System Oversight & Compliance</h2>
                            <p>All submissions to the Atlash System Directory undergo a mandatory Compliance Review. Our oversight team reserves the right to de-list any node that fails to meet the 100% architectural integrity standards required for the Atlash Industry Trust Index.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-black text-foreground uppercase tracking-tight">4. Reliability Metrics</h2>
                            <p>Verification votes and trust scores generated by our corporate users are intended for benchmarking purposes only. Atlash Hub does not assume liability for 3rd party infrastructure failures; users must perform their own due diligence during procurement.</p>
                        </section>
                    </div>
                </div>
            </div>
        </main>
    );
}